import Scroll from '@/components/scroll-fixture';
import Providers from '@/components/wrapper/providers';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <head />
      <body className="background">
        <Providers>{children}</Providers>
      </body>
      <Scroll />
    </html>
  );
}
