import Providers from '@/components/providers';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <Providers>
        <UserProvider>
          <body>{children}</body>
        </UserProvider>
      </Providers>
    </html>
  );
}
