import Scroll from '@/components/scroll-fixture';
import Providers from '@/components/wrapper/providers';
import type { Metadata } from 'next';
import { Lora, Poppins } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
  style: ['italic', 'normal'],
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
  display: 'swap'
});

const lora = Lora({ subsets: ['latin'], display: 'swap', variable: '--font-lora' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <head />
      <body className={`background ${poppins.variable} ${lora.variable}`}>
        <Providers>{children}</Providers>
      </body>
      <Scroll />
    </html>
  );
}
