"""move_ingredient_meal_to_associate_object

Revision ID: fce3bc470927
Revises: a9d963f81fb5
Create Date: 2024-08-29 13:55:36.853084

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "fce3bc470927"
down_revision = "a9d963f81fb5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "ingredient_meal",
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "ingredient_meal",
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "ingredient_meal",
        "unit",
        existing_type=postgresql.ENUM(
            "MILLIGRAMME",
            "GRAMME",
            "MILLILITRE",
            "CENTILITRE",
            "LITRE",
            "CUILLIERE_CAFE",
            "CUILLIERE_SOUPE",
            "UNITE",
            name="unitenum",
        ),
        nullable=False,
    )
    op.drop_constraint(
        "ingredient_meal_ingredient_id_meal_id_key", "ingredient_meal", type_="unique"
    )
    op.drop_constraint("fk_meal_user_id", "meal", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_meal_user_id",
        "meal",
        "user_account",
        ["user_id"],
        ["user_id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        "ingredient_meal_ingredient_id_meal_id_key",
        "ingredient_meal",
        ["ingredient_id", "meal_id"],
    )
    op.alter_column(
        "ingredient_meal",
        "unit",
        existing_type=postgresql.ENUM(
            "MILLIGRAMME",
            "GRAMME",
            "MILLILITRE",
            "CENTILITRE",
            "LITRE",
            "CUILLIERE_CAFE",
            "CUILLIERE_SOUPE",
            "UNITE",
            name="unitenum",
        ),
        nullable=True,
    )
    op.drop_column("ingredient_meal", "update_time")
    op.drop_column("ingredient_meal", "create_time")

    # ### end Alembic commands ###
