"""fix

Revision ID: 81d98cc6f821
Revises: 3d2c78bfde45
Create Date: 2024-08-14 16:29:11.776513

"""



# revision identifiers, used by Alembic.
revision = "81d98cc6f821"
down_revision = "3d2c78bfde45"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
