"""add_geo_location

Revision ID: 90e3f6cd31ed
Revises: eaf06b874725
Create Date: 2024-08-23 14:22:24.708072

"""

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "90e3f6cd31ed"
down_revision = "eaf06b874725"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "address",
        sa.Column(
            "geo_location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("address", "geo_location")
    # ### end Alembic commands ###
