"""remove cascade in user for address

Revision ID: eb3eb4e896aa
Revises: 344a9429646a
Create Date: 2024-08-21 17:45:28.342357

"""

# revision identifiers, used by Alembic.
revision = "eb3eb4e896aa"
down_revision = "344a9429646a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
