"""add_unique_for_openid

Revision ID: 4521e987844b
Revises: 763f63179a09
Create Date: 2024-09-03 15:43:20.130395

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "4521e987844b"
down_revision = "763f63179a09"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_unique_constraint(None, "user_account", ["open_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_account", type_="unique")

    # ### end Alembic commands ###
