"""add_residency_in_user

Revision ID: ebf5ad028eec
Revises: 9421a403ef8e
Create Date: 2024-09-03 10:07:04.269670

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ebf5ad028eec"
down_revision = "9421a403ef8e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "address", sa.Column("resident_id", sa.Uuid(as_uuid=False), nullable=True)
    )
    op.create_foreign_key(None, "address", "user_account", ["resident_id"], ["user_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "address", type_="foreignkey")
    op.drop_column("address", "resident_id")
