"""add_relation_with_order

Revision ID: f2699cf88fc8
Revises: ddf1efd516d4
Create Date: 2024-10-19 18:11:37.904085

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f2699cf88fc8"
down_revision = "ddf1efd516d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column("chat", sa.Column("order_id", sa.Uuid(as_uuid=False), nullable=True))
    op.create_unique_constraint(None, "chat", ["order_id"])
    op.create_foreign_key(None, "chat", "order", ["order_id"], ["order_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chat", type_="foreignkey")
    op.drop_constraint(None, "chat", type_="unique")
    op.drop_column("chat", "order_id")

    # ### end Alembic commands ###
