"""add_is_ordered_in_meal

Revision ID: 5276cd125266
Revises: 20934bee1d5d
Create Date: 2024-09-18 11:14:04.913681

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "5276cd125266"
down_revision = "20934bee1d5d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("COMPLETED", "CANCELLED", name="statussenum").create(op.get_bind())

    op.add_column(
        "meal",
        sa.Column(
            "is_ordered", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.add_column(
        "order",
        sa.Column(
            "status",
            postgresql.ENUM(
                "COMPLETED",
                "CANCELLED",
                name="statussenum",
                create_constraint=True,
                create_type=False,
            ),
            nullable=False,
        ),
    )
    op.create_unique_constraint(None, "user_account", ["user_sub"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_account", type_="unique")
    op.drop_column("order", "status")
    op.drop_column("meal", "is_ordered")

    sa.Enum("COMPLETED", "CANCELLED", name="statussenum").drop(op.get_bind())
    # ### end Alembic commands ###
