"""add default arr in meals user

Revision ID: 6c8fe52936cf
Revises: 4d9c261fca44
Create Date: 2024-08-15 11:00:22.354791

"""



# revision identifiers, used by Alembic.
revision = "6c8fe52936cf"
down_revision = "4d9c261fca44"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
