"""remove foreign key in meals

Revision ID: 37bb2ac61376
Revises: e1bdf94444a5
Create Date: 2024-08-22 14:51:53.177504

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "37bb2ac61376"
down_revision = "e1bdf94444a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("address_meals_id_fkey", "address", type_="foreignkey")
    op.drop_column("address", "meals_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "address", sa.Column("meals_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        "address_meals_id_fkey", "address", "meal", ["meals_id"], ["meal_id"]
    )
    # ### end Alembic commands ###
