"""cascade_on_ingredient_meal_meal_id

Revision ID: a9d963f81fb5
Revises: 97fad11b67d8
Create Date: 2024-08-29 12:12:56.959982

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "a9d963f81fb5"
down_revision = "97fad11b67d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        "ingredient_meal_meal_id_fkey", "ingredient_meal", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "ingredient_meal", "meal", ["meal_id"], ["meal_id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ingredient_meal", type_="foreignkey")
    op.create_foreign_key(
        "ingredient_meal_meal_id_fkey",
        "ingredient_meal",
        "meal",
        ["meal_id"],
        ["meal_id"],
    )

    # ### end Alembic commands ###
