"""remove delete all orphans

Revision ID: 4d9c261fca44
Revises: 1d14c35b4b1d
Create Date: 2024-08-14 21:47:53.077849

"""



# revision identifiers, used by Alembic.
revision = "4d9c261fca44"
down_revision = "1d14c35b4b1d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
