"""remove_isvalid_and_change_phonenumber_to_str

Revision ID: 763f63179a09
Revises: fd606aacaae7
Create Date: 2024-09-03 15:19:14.266778

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "763f63179a09"
down_revision = "fd606aacaae7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "user_account",
        "phone_number",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=256),
        existing_nullable=True,
    )
    op.drop_column("user_account", "is_valid")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_account",
        sa.Column(
            "is_valid",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "user_account",
        "phone_number",
        existing_type=sa.String(length=256),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )

    # ### end Alembic commands ###
