"""add_picture_url_in_user

Revision ID: 8642fccf07a6
Revises: 4e43454be281
Create Date: 2024-09-03 09:21:42.935007

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8642fccf07a6"
down_revision = "4e43454be281"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "user_account", sa.Column("picture_url", sa.String(length=256), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "picture_url")

    # ### end Alembic commands ###
