"""fix

Revision ID: 3d2c78bfde45
Revises:
Create Date: 2024-08-14 16:07:00.875284

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3d2c78bfde45"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredient",
        sa.Column("ingredient_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("ingredient_id"),
    )
    op.create_table(
        "user_account",
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("open_id", sa.String(length=256), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "meal",
        sa.Column("meal_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.user_id"],
        ),
        sa.PrimaryKeyConstraint("meal_id"),
    )
    op.create_table(
        "ingredient_meal",
        sa.Column("ingredient_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("meal_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredient.ingredient_id"],
        ),
        sa.ForeignKeyConstraint(
            ["meal_id"],
            ["meal.meal_id"],
        ),
        sa.PrimaryKeyConstraint("ingredient_id", "meal_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ingredient_meal")
    op.drop_table("meal")
    op.drop_table("user_account")
    op.drop_table("ingredient")
    # ### end Alembic commands ###
