"""add_finalize_status_in_order

Revision ID: 6c3f1178d7bb
Revises: 5276cd125266
Create Date: 2024-10-14 11:15:33.552051

"""

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision = "6c3f1178d7bb"
down_revision = "5276cd125266"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.sync_enum_values(
        "public",
        "statussenum",
        ["COMPLETED", "CANCELLED", "FINALIZED"],
        [
            TableReference(
                table_schema="public", table_name="order", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "statussenum",
        ["COMPLETED", "CANCELLED"],
        [
            TableReference(
                table_schema="public", table_name="order", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )

    # ### end Alembic commands ###
