"""add_username_field

Revision ID: b2ba2609575c
Revises: 8642fccf07a6
Create Date: 2024-09-03 09:28:39.702344

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b2ba2609575c"
down_revision = "8642fccf07a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "user_account", sa.Column("username", sa.String(length=35), nullable=True)
    )
    op.alter_column(
        "user_account",
        "first_name",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.String(length=35),
        existing_nullable=True,
    )
    op.alter_column(
        "user_account",
        "last_name",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.String(length=35),
        existing_nullable=True,
    )
    op.alter_column(
        "user_account",
        "phone_number",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.Integer(),
        existing_nullable=True,
        **{"using": "phone_number::integer"},
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_account",
        "phone_number",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=256),
        existing_nullable=True,
    )
    op.alter_column(
        "user_account",
        "last_name",
        existing_type=sa.String(length=35),
        type_=sa.VARCHAR(length=256),
        existing_nullable=True,
    )
    op.alter_column(
        "user_account",
        "first_name",
        existing_type=sa.String(length=35),
        type_=sa.VARCHAR(length=256),
        existing_nullable=True,
    )
    op.drop_column("user_account", "username")

    # ### end Alembic commands ###
