"""remove_kg

Revision ID: eaf06b874725
Revises: 123f8c8214d7
Create Date: 2024-08-23 10:54:43.151964

"""

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision = "eaf06b874725"
down_revision = "123f8c8214d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "unitenum",
        [
            "MILLIGRAMME",
            "GRAMME",
            "MILLILITRE",
            "CENTILITRE",
            "LITRE",
            "CUILLIERE_CAFE",
            "CUILLIERE_SOUPE",
            "UNITE",
        ],
        [
            TableReference(
                table_schema="public", table_name="ingredient_meal", column_name="unit"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "unitenum",
        [
            "MILLIGRAMME",
            "GRAMME",
            "KILLOGRAMME",
            "MILLILITRE",
            "CENTILITRE",
            "LITRE",
            "CUILLIERE_CAFE",
            "CUILLIERE_SOUPE",
            "UNITE",
        ],
        [
            TableReference(
                table_schema="public", table_name="ingredient_meal", column_name="unit"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
