"""fix_enum

Revision ID: 5970334c15f7
Revises: 7127c080537d
Create Date: 2024-08-23 09:44:10.107053

"""

# revision identifiers, used by Alembic.
revision = "5970334c15f7"
down_revision = "7127c080537d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
