"""add_non_nullabe_for_username

Revision ID: 9421a403ef8e
Revises: b2ba2609575c
Create Date: 2024-09-03 09:35:44.892158

"""

# revision identifiers, used by Alembic.
revision = "9421a403ef8e"
down_revision = "b2ba2609575c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
