"""add_uniqueness_constraint_for_email

Revision ID: 8ccc11aaa7e0
Revises: 4521e987844b
Create Date: 2024-09-04 11:43:43.480588

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "8ccc11aaa7e0"
down_revision = "4521e987844b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_unique_constraint(None, "user_account", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_account", type_="unique")

    # ### end Alembic commands ###
