"""add_relation_with_order

Revision ID: e03c7235313c
Revises: f2699cf88fc8
Create Date: 2024-10-19 18:12:17.350536

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e03c7235313c"
down_revision = "f2699cf88fc8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column("chat", "order_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chat", "order_id", existing_type=sa.UUID(), nullable=True)

    # ### end Alembic commands ###
