"""adding foreignkey in address

Revision ID: c4ad40d905c2
Revises: eb3eb4e896aa
Create Date: 2024-08-21 17:46:55.018715

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c4ad40d905c2"
down_revision = "eb3eb4e896aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "address", sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False)
    )
    op.add_column(
        "address", sa.Column("meals_id", sa.Uuid(as_uuid=False), nullable=False)
    )
    op.create_foreign_key(None, "address", "meal", ["meals_id"], ["meal_id"])
    op.create_foreign_key(None, "address", "user_account", ["user_id"], ["user_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "address", type_="foreignkey")
    op.drop_constraint(None, "address", type_="foreignkey")
    op.drop_column("address", "meals_id")
    op.drop_column("address", "user_id")
    # ### end Alembic commands ###
