"""add_message_and_chat

Revision ID: ddf1efd516d4
Revises: 95433ed0ebf0
Create Date: 2024-10-19 17:58:21.957925

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ddf1efd516d4"
down_revision = "95433ed0ebf0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat",
        sa.Column("chat_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("user1_sub", sa.String(length=256), nullable=False),
        sa.Column("user2_sub", sa.String(length=256), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user1_sub"],
            ["user_account.user_sub"],
        ),
        sa.ForeignKeyConstraint(
            ["user2_sub"],
            ["user_account.user_sub"],
        ),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.create_table(
        "message",
        sa.Column("message_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("content", sa.String(length=1000), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("chat_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("sender_sub", sa.String(length=256), nullable=False),
        sa.Column("receiver_sub", sa.String(length=256), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chat.chat_id"],
        ),
        sa.ForeignKeyConstraint(
            ["receiver_sub"],
            ["user_account.user_sub"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_sub"],
            ["user_account.user_sub"],
        ),
        sa.PrimaryKeyConstraint("message_id"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("message")
    op.drop_table("chat")
    # ### end Alembic commands ###
