"""fix_enum

Revision ID: 123f8c8214d7
Revises: 5970334c15f7
Create Date: 2024-08-23 09:48:04.293526

"""

# revision identifiers, used by Alembic.
revision = "123f8c8214d7"
down_revision = "5970334c15f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
