"""fix_enum

Revision ID: 7127c080537d
Revises: e8d1a7206e83
Create Date: 2024-08-23 09:33:28.036720

"""

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision = "7127c080537d"
down_revision = "e8d1a7206e83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "unitenum",
        [
            "MILLIGRAMME",
            "GRAMME",
            "KILLOGRAMME",
            "MILLILITRE",
            "CENTILITRE",
            "LITRE",
            "CUILLIERE_CAFE",
            "CUILLIERE_SOUPE",
            "UNITE",
        ],
        [
            TableReference(
                table_schema="public", table_name="ingredient_meal", column_name="unit"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "unitenum",
        [
            "milligramme",
            "gramme",
            "kilogramme",
            "millilitre",
            "centilitre",
            "litre",
            "cuillière_cafe",
            "cuillière_soupe",
            "unite",
        ],
        [
            TableReference(
                table_schema="public", table_name="ingredient_meal", column_name="unit"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
