"""rename_picture_url_to_picture_key

Revision ID: c28f6919dd90
Revises: d2c236b6786d
Create Date: 2024-09-10 17:38:18.021821

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "c28f6919dd90"
down_revision = "d2c236b6786d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column("meal", "picture_url", new_column_name="picture_key")
    op.alter_column("user_account", "picture_url", new_column_name="picture_key")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column("meal", "picture_key", new_column_name="picture_url")
    op.alter_column("user_account", "picture_key", new_column_name="picture_url")

    # ### end Alembic commands ###
