"""add key column in meal

Revision ID: d2029afef706
Revises: ddc69dae52c7
Create Date: 2024-08-16 14:16:37.213164

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d2029afef706"
down_revision = "ddc69dae52c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meal", sa.Column("picture_key", sa.String(length=256), nullable=True)
    )
    op.drop_column("meal", "pictureKey")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meal",
        sa.Column(
            "pictureKey", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("meal", "picture_key")
    # ### end Alembic commands ###
