"""add key column in meal

Revision ID: ddc69dae52c7
Revises: 6c8fe52936cf
Create Date: 2024-08-16 14:15:49.351623

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ddc69dae52c7"
down_revision = "6c8fe52936cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("meal", sa.Column("pictureKey", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meal", "pictureKey")
    # ### end Alembic commands ###
