"""add pi_id in order

Revision ID: e03b89c3c486
Revises: 29a72ffb3140
Create Date: 2024-10-14 18:12:23.439600

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e03b89c3c486"
down_revision = "29a72ffb3140"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "order",
        sa.Column(
            "pi_id",
            sa.String(length=256),
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
        ),
    )
    op.create_unique_constraint(None, "order", ["pi_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order", type_="unique")
    op.drop_column("order", "pi_id")

    # ### end Alembic commands ###
