"""remove delete all orphans

Revision ID: 1d14c35b4b1d
Revises: af79e570faca
Create Date: 2024-08-14 21:47:11.708558

"""



# revision identifiers, used by Alembic.
revision = "1d14c35b4b1d"
down_revision = "af79e570faca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
