"""add mandatory for address and user in meal

Revision ID: e1bdf94444a5
Revises: 0491f6e36fba
Create Date: 2024-08-22 14:40:00.631836

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e1bdf94444a5"
down_revision = "0491f6e36fba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meal", sa.Column("address_id", sa.Uuid(as_uuid=False), nullable=False)
    )
    op.create_foreign_key(None, "meal", "address", ["address_id"], ["address_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "meal", type_="foreignkey")
    op.drop_column("meal", "address_id")
    # ### end Alembic commands ###
