"""add_isvalid_in_user

Revision ID: fd606aacaae7
Revises: ebf5ad028eec
Create Date: 2024-09-03 14:46:04.285053

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fd606aacaae7"
down_revision = "ebf5ad028eec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "user_account",
        sa.Column(
            "is_valid", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "is_valid")

    # ### end Alembic commands ###
