"""add_about_me_in_user

Revision ID: d2c236b6786d
Revises: 8ccc11aaa7e0
Create Date: 2024-09-09 14:54:41.122352

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d2c236b6786d"
down_revision = "8ccc11aaa7e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "user_account", sa.Column("about_me", sa.String(length=256), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "about_me")

    # ### end Alembic commands ###
