"""add unique constraint on ingredient name

Revision ID: 73648e90e0a9
Revises: 81d98cc6f821
Create Date: 2024-08-14 19:59:51.005064

"""


from alembic import op

# revision identifiers, used by Alembic.
revision = "73648e90e0a9"
down_revision = "81d98cc6f821"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "ingredient", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ingredient", type_="unique")
    # ### end Alembic commands ###
