"""add_order_class

Revision ID: 0f90ff2984bf
Revises: c28f6919dd90
Create Date: 2024-09-13 11:02:56.423575

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0f90ff2984bf"
down_revision = "c28f6919dd90"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("order_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("meal_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meal_id"],
            ["meal.meal_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.user_id"],
        ),
        sa.PrimaryKeyConstraint("order_id"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order")
    # ### end Alembic commands ###
