"""nullable_true_for_unit_in_ingredient_meal

Revision ID: 408aa4bfe2d7
Revises: fce3bc470927
Create Date: 2024-08-29 14:09:08.357509

"""

from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "408aa4bfe2d7"
down_revision = "fce3bc470927"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "ingredient_meal",
        "unit",
        existing_type=postgresql.ENUM(
            "MILLIGRAMME",
            "GRAMME",
            "MILLILITRE",
            "CENTILITRE",
            "LITRE",
            "CUILLIERE_CAFE",
            "CUILLIERE_SOUPE",
            "UNITE",
            name="unitenum",
        ),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ingredient_meal",
        "unit",
        existing_type=postgresql.ENUM(
            "MILLIGRAMME",
            "GRAMME",
            "MILLILITRE",
            "CENTILITRE",
            "LITRE",
            "CUILLIERE_CAFE",
            "CUILLIERE_SOUPE",
            "UNITE",
            name="unitenum",
        ),
        nullable=False,
    )

    # ### end Alembic commands ###
