name: FastAPI CI

env:
  TF_LOG: INFO
  TF_INPUT: false
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

on:
  workflow_dispatch:

concurrency: 
  group: build
  cancel-in-progress: true

jobs:
  IaC:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
       
      - name: Initialize Terraform
        run: |
          terraform fmt
          terraform init

      - name: Plan Terraform changes
        run: terraform plan -no-color

      - name: Apply Terraform changes (optional, requires confirmation)
        run: terraform apply -auto-approve
