name: AWS-EC2 Instance CD

on:
  workflow_dispatch: 

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@v1.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          instance-ids: ${{ secrets.AWS_INSTANCE_ID }}
          working-directory: /home/ubuntu
          command: |
            sudo docker stop nextjs-app
            sudo docker rm nextjs-app
            sudo docker pull ${{secrets.DOCKER_HUB_USERNAME}}/dine-dong-fe:latest
            sudo docker run -d --name nextjs-app --publish 3000:3000 ${{secrets.DOCKER_HUB_USERNAME}}/dine-dong-fe:latest
          comment: Pulls the latest dine-dong-fe image and runs it on the instance.