name: FastAPI CI

env:
  TF_LOG: INFO
  TF_INPUT: false

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths:
      - 'backend/**'
      - 'terraform/**'
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'backend/**'
      - 'terraform/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
       
      - name: Initialize Terraform
        run: |
          terraform fmt
          terraform init
        env:
          REGION: ${{ secrets.TF_VAR_REGION }}
          API_DOMAIN_NAME: ${{ secrets.TF_VAR_API_DOMAIN_NAME }}
          DOMAIN_NAME_CERTIFICATE_ARN: ${{ secrets.TF_VAR_DOMAIN_NAME_CERTIFICATE_ARN }}
        
      - name: Plan Terraform changes
        run: terraform plan -no-color -var REGION=${{ secrets.TF_VAR_REGION }} -var API_DOMAIN_NAME=${{ secrets.TF_VAR_API_DOMAIN_NAME }} -var DOMAIN_NAME_CERTIFICATE_ARN=${{ secrets.TF_VAR_DOMAIN_NAME_CERTIFICATE_ARN }}

      - name: Apply Terraform changes (optional, requires confirmation)
        run: terraform apply -auto-approve
          
            
         

