name: FastAPI CI

env:
  TF_LOG: INFO
  TF_INPUT: false

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths:
      - 'backend/**'
      - 'terraform/**'
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'backend/**'
      - 'terraform/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
       
      - name: Initialize Terraform
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          REGION: ${{ secrets.TF_VAR_REGION }}
          API_DOMAIN_NAME: ${{ secrets.TF_VAR_API_DOMAIN_NAME }}
          DOMAIN_NAME_CERTIFICATE_ARN: ${{ secrets.TF_VAR_DOMAIN_NAME_CERTIFICATE_ARN }}
        
      - name: Plan Terraform changes
        run: terraform plan -no-color -var REGION=${{ secrets.TF_VAR_REGION }} -var API_DOMAIN_NAME=${{ secrets.TF_VAR_API_DOMAIN_NAME }} -var DOMAIN_NAME_CERTIFICATE_ARN=${{ secrets.TF_VAR_DOMAIN_NAME_CERTIFICATE_ARN }}

      - name: Apply Terraform changes (optional, requires confirmation)
        run: |
          if [[ $(git diff --cached --name-only | grep -qE '^\.terraform/') ]]; then
            terraform apply -auto-approve
          else
            echo "No changes detected in Terraform configuration. Skipping apply."
          fi

