name: Format Linting and Typecheck

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint_client: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup-bun
      - name: Lint
        run: |
          cd ./client
          bun lint

  format_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup-bun
      - name: Format
        run: |
          cd ./client
          bun prettier:check

  typecheck_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup-bun
      - name: Typecheck
        run: |
          cd ./client
          bun typecheck

  typecheck_server:
    strategy:
      matrix:
        check: ["ruff check", "ruff format --check"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        run: |
          cd server
          python3 -m venv .venv
          source .venv/bin/activate

      - name: Install Poetry
        run: |
          cd server
          pip install poetry

      - name: Install dependencies
        run: |
          cd server
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-root

      - name: Run ${{ matrix.check }}
        run: |
          cd server
          poetry run ${{ matrix.check }} .

  trigger-workflows:
    needs: [lint_client, format_client, typecheck_client, typecheck_server]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get all test, doc and src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            client: 
              - client/**
              - .github/workflows/client-build.yml
            server:
              - server/**
              - .github/workflows/backend-to-lambda.yml
              - terraform/**

      - name: Trigger NextJS Build and Push Workflow
        if: steps.changed-files-yaml.outputs.client_any_changed == 'true'
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.API_GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/dobzacode/dine-dong/actions/workflows/client-build.yml/dispatches \
            -d '{"ref":"main"}'

      
